<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>ppa.lab</groupId>
        <artifactId>ppa-libs-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <groupId>ppa.spring</groupId>
    <artifactId>spring-framework-learning</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>


    <modules>
        <module>simple-autoconfiguration-starter</module>
        <module>spring-framework-di</module>
        <module>spring-framework-profile</module>
        <module>spring-framework-beanlifecycle</module>
        <module>spring-framework-transaction</module>
        <module>spring-framework-simplewebapp</module>
        <module>spring-framework-scheduler</module>
        <module>spring-framework-controlleradvice</module>
        <module>spring-data-access</module>
        <module>spring-pagination</module>
        <module>ia</module>
    </modules>

    <properties>
        <mysql.version>8.0.33</mysql.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
        </dependency>
    </dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>net.ttddyy</groupId>
                <artifactId>datasource-proxy</artifactId>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
            </dependency>
            <dependency>
                <groupId>ppa.spring</groupId>
                <artifactId>spring-framework-di</artifactId>
            </dependency>
            <dependency>
                <groupId>ppa.lab</groupId>
                <artifactId>model-tools</artifactId>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>