package ppa.labs.springbatch.model.enums;

public enum CsvVaersHeader {
    VAERS_ID
    ,RECVDATE
    ,STATE
    ,AGE_YRS
    ,CAGE_YR
    ,CAGE_MO
    ,SEX
    ,RPT_DATE
    ,SYMPTOM_TEXT
    ,DIED
    ,DATEDIED
    ,L_THREAT
    ,ER_VISIT
    ,HOSPITAL
    ,HOSPDAYS
    ,X_STAY
    ,DISABLE
    ,RECOVD
    ,VAX_DATE
    ,ONSET_DATE
    ,NUMDAYS
    ,LAB_DATA
    ,V_ADMINBY
    ,V_FUNDBY
    ,OTHER_MEDS
    ,CUR_ILL
    ,HISTORY
    ,PRIOR_VAX
    ,SPLTTYPE
    ,FORM_VERS
    ,TODAYS_DATE
    ,BIRTH_DEFECT
    ,OFC_VISIT
    ,ER_ED_VISIT
    ,ALLERGIES
    }
